import {
  siClaude,
  siClickup,
  siCursor,
  siDeepseek,
  siElevenlabs,
  siFreepik,
  siGithubcopilot,
  siGooglegemini,
  siGrammarly,
  siKuaishou,
  siMistralai,
  siN8n,
  siNotebooklm,
  siNotion,
  siPerplexity,
  siRemovedotbg,
  siReplit,
  siStackblitz,
  siSuno,
  siV0,
  siWindsurf,
} from "simple-icons";

/** Monochrome brand marks from Simple Icons (CC0), keyed by tool slug. */
export const BRAND_ICONS: Record<string, { title: string; path: string }> = {
  claude: siClaude,
  clickup: siClickup,
  cursor: siCursor,
  deepseek: siDeepseek,
  elevenlabs: siElevenlabs,
  freepik: siFreepik,
  "github-copilot": siGithubcopilot,
  gemini: siGooglegemini,
  grammarly: siGrammarly,
  kling: siKuaishou,
  mistral: siMistralai,
  n8n: siN8n,
  notebooklm: siNotebooklm,
  notion: siNotion,
  perplexity: siPerplexity,
  "remove-bg": siRemovedotbg,
  replit: siReplit,
  bolt: siStackblitz,
  suno: siSuno,
  v0: siV0,
  windsurf: siWindsurf,
};
