import {
  siClaude,
  siClickup,
  siCline,
  siCursor,
  siDeepl,
  siDeepseek,
  siElevenlabs,
  siFreepik,
  siGithubcopilot,
  siGoogle,
  siGooglegemini,
  siGrammarly,
  siHuggingface,
  siJetbrains,
  siKimi,
  siKuaishou,
  siMake,
  siMeta,
  siMinimax,
  siMistralai,
  siN8n,
  siNotebooklm,
  siNotion,
  siPerplexity,
  siPicsart,
  siPoe,
  siQwen,
  siRemovedotbg,
  siReplit,
  siSemrush,
  siStackblitz,
  siSuno,
  siV0,
  siVeed,
  siWarp,
  siWindsurf,
  siZapier,
} from "simple-icons";

/** Monochrome brand marks from Simple Icons (CC0), keyed by tool slug. */
export const BRAND_ICONS: Record<string, { title: string; path: string }> = {
  bolt: siStackblitz,
  claude: siClaude,
  clickup: siClickup,
  cline: siCline,
  cursor: siCursor,
  deepl: siDeepl,
  deepseek: siDeepseek,
  elevenlabs: siElevenlabs,
  freepik: siFreepik,
  gemini: siGooglegemini,
  "github-copilot": siGithubcopilot,
  "google-ai-studio": siGoogle,
  "google-flow": siGoogle,
  grammarly: siGrammarly,
  hailuo: siMinimax,
  "hugging-face": siHuggingface,
  "jetbrains-ai": siJetbrains,
  kimi: siKimi,
  kling: siKuaishou,
  make: siMake,
  "meta-ai": siMeta,
  mistral: siMistralai,
  n8n: siN8n,
  notebooklm: siNotebooklm,
  notion: siNotion,
  perplexity: siPerplexity,
  picsart: siPicsart,
  poe: siPoe,
  qwen: siQwen,
  "remove-bg": siRemovedotbg,
  replit: siReplit,
  semrush: siSemrush,
  suno: siSuno,
  v0: siV0,
  veed: siVeed,
  warp: siWarp,
  windsurf: siWindsurf,
  zapier: siZapier,
};
